### ISSUE TITLE
How to enable Keep-Alive?

### ISSUE THREAD

**Issue by curusarn** [ufal/microrestd#1]
How to make `microrestd` send `Connection: Keep-Alive`  header?
I'm asking because [nametag](https://github.com/ufal/nametag) REST server is not sending `Connection: Keep-Alive` header. (afaik)
It seems that `libmicrohttpd` sends the `Connection: Keep-Alive` header by default but `microrestd` does not.

I have noticed that `tests/libmicrohttpd_fileserver` sends `Connection: Keep-Alive`  header but `tests/fileserver` does not.

**Reproduce/What I did**

Compile tests.
```
cd tests
make
echo "FILE_CONTENT" > filename # create dummy file
```

Run `tests/libmicrohttpd_fileserver`
```
>>> ./libmicrohttpd_fileserver 8080
Running...
```

Test `Keep-Alive`
```
>>> curl -v 'http://127.0.0.1:8080/filename' --keepalive-time 42
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /filename HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Connection: Keep-Alive
< Content-Length: 13
< Date: Tue, 20 Feb 2018 16:27:15 GMT
< 
FILE_CONTENT
* Connection #0 to host 127.0.0.1 left intact
```
**Notice `< Connection: Keep-Alive` and `* Connection #0 to host 127.0.0.1 left intact`.**

---

Run `tests/fileserver`
```
>>> ./fileserver 8080 10 10
Tue 20. Feb 2018 17:27:31	REST server starting, port 8080, max connections 10, timeout 0, max request body size 0, min generated 1024.
```

Test `Keep-Alive`
```
>>> curl -v 'http://127.0.0.1:8080/filename' --keepalive-time 42
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /filename HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Connection: close
< Access-Control-Allow-Origin: *
< Content-Type: application/octet-stream
< Date: Tue, 20 Feb 2018 16:27:37 GMT
< 
FILE_CONTENT
* Closing connection 0
```
**Notice `< Connection: close` and `* Closing connection 0`.**

**Comment by foxik** [comment]
We are adding Connection: close deliberately at https://github.com/ufal/microrestd/blob/master/src/rest_server/rest_server.cpp#L258. All our servers are behind (actually several) proxies, so we do not care about it.

If you want to create a pull request which would add a new rest_server::set_xxx method to disable this behaviour (with the default being to add Connection: close), I will happily accept it.
